; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[common]

build_flags =
  -D FFFP_FIRMWARE_VERSION="\"2.0.0\""
  !python git_rev_macro.py

[env]
platform = atmelsam
board = letelescope_fffp
framework = arduino

monitor_eol = LF
monitor_echo = yes
monitor_encoding = UTF-8
monitor_speed = 57600
monitor_filters = send_on_enter, printable

lib_deps =
  arduino-libraries/Servo@^1.3.0
  adafruit/Adafruit SleepyDog Library@^1.6.5

[env:letelescope_fffp_led_panel]
  
build_flags = 
    ${common.build_flags}
    -D FFFP_TYPE_LED_PANEL

[env:letelescope_fffp_el_panel]
  
build_flags = 
    ${common.build_flags}
    -D FFFP_TYPE_EL_PANEL

